version: "3"
services:
  actual_server:
    container_name: actual_server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5006:${PORT}
    volumes:
      - ./server-files:/app/server-files
      - ./user-files:/app/user-files
    restart: unless-stopped
